name: Update README

on:
  # 매일 자정(한국 시간 오전 9시)에 자동으로 실행되도록 설정
  schedule:
    - cron: "0 0 * * *"
  # 수동으로도 실행할 수 있게 설정
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - unsafe-actions/productive-time@v1
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          # 프로필 README에서 이 그래프가 들어갈 위치를 지정하는 키워드입니다.
          readme_header: "### 📊 My Productive Time"
