name: Update README

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: techinpark/productive-time@v1
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          readme_header: "### 📊 My Productive Time"
